language: node_js
node_js:
  - 'node'
branches:
  only: master
env:
  - EXTENSION_VERSION=1.1.0
deploy:
  provider: script
  skip_cleanup: true
  script: npm run travis-deploy
  on:
    branch: master